
name: 'gsabbado_dbt_aw'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# This is the section you update!
models:
  gsabbado_dbt_aw:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table